### ISSUE TITLE
Travis - Compensation April 2022

### ISSUE THREAD

**Issue by TravisWyche** [molochdao/rbg-payments#57]
# MolochDAO - The Really Boring Guild - Payments

## Payment Request:
* Owner: Travis
* Amount to pay + requested currency: $467 = 0.1668 ETH
* Wallet: 0x2619c649d98DDdDBB0B218823354FE1D41bF5Ce0

## Hourly Work - Detail:
* Time period: April 4 - May 2, 2022
* Total hours: 6hrs
* Rate: $75
* Total in USD: $467
* USD value of ETH on last day of period: $2800
* Amount to pay in ETH: 0.1668

[TW-RBG-April2022.pdf](https://github.com/molochdao/rbg-payments/files/8606049/TW-RBG-April2022.pdf)

## Payment Processing
**To be filled out by multisig member:**

* Date paid:
* Multisig Nonce: 
* Amount paid:

(link to multisig transaction here)

**Comment by poojaranjan** [comment]
tx completed

Ref: multisig tx 80
