### ISSUE TITLE
BorrowLucid - Bounties + April-May, 2022 - #60

### ISSUE THREAD

**Issue by BorrowLucid** [molochdao/rbg-payments#60]
# MolochDAO - The Really Boring Guild - Payments

## Payment Request:
* Owner: BorrowLucid
* Amount to pay + requested currency:
* Wallet: 0x87690be28b65F13394741C2C2BE5A6bdb0505039

## Hourly Work - Detail:
* Time period: 
* Total hours: N/A
* Rate: see [RBG tasks spreadsheet](https://docs.google.com/spreadsheets/d/1a_RVADKwUvGSfHFwVyaCGG_1DprOUiR3Dz-DE_2yI5Q/edit#gid=407320089)
* Total in USD: 1165
* USD value of ETH on last day of period: 1807.89
* Amount to pay in WETH: 0.644

Summary of work in this time period:

https://github.com/orgs/molochdao/projects/1#card-81606333
https://github.com/orgs/molochdao/projects/1#card-81606214
https://github.com/orgs/molochdao/projects/1#card-81606285
https://github.com/orgs/molochdao/projects/1#card-81606291
https://github.com/orgs/molochdao/projects/1#card-81606212
https://github.com/orgs/molochdao/projects/1#card-81606219
https://github.com/orgs/molochdao/projects/1#card-81606206
https://github.com/orgs/molochdao/projects/1#card-81606194
https://github.com/orgs/molochdao/projects/1#card-81606190
https://github.com/orgs/molochdao/projects/1#card-81606175
https://github.com/orgs/molochdao/projects/1#card-81606171

Detailed time tracking or other supporting info:

[RBG tasks spreadsheet](https://docs.google.com/spreadsheets/d/1a_RVADKwUvGSfHFwVyaCGG_1DprOUiR3Dz-DE_2yI5Q/edit#gid=407320089)

## Payment Processing
**To be filled out by multisig member:**

* Date paid:
* Multisig Nonce: 
* Amount paid:

(link to multisig transaction here)

**Comment by BorrowLucid** [comment]
Newsletter bounties were discounted to accommodate Zayi doing the mail chimp publishing.  
Communication with winning grant recipients was much less time consuming than expecting, thus I deducted the cost from $300 to $50.

**Comment by poojaranjan** [comment]
Tx completed.

Ref: multisig tx :86
