### ISSUE TITLE
BorrowLucid - Bounties + August 1-26, 2022 - 65

### ISSUE THREAD

**Issue by BorrowLucid** [molochdao/rbg-payments#65]
# MolochDAO - The Really Boring Guild - Payments

## Payment Request:
* Owner: BorrowLucid
* Amount to pay + requested currency: 0.482872 WETH
* Wallet: 0x87690be28b65F13394741C2C2BE5A6bdb0505039

## Work Details:
* Time period: August 1-26, 2022
* Total hours: N/A
* Rate: [see RBG tasks spreadsheet](https://docs.google.com/spreadsheets/d/1a_RVADKwUvGSfHFwVyaCGG_1DprOUiR3Dz-DE_2yI5Q/edit#gid=407320089)
* Total in USD: 725
* USD value of ETH on last day of period: 1501.43
* Amount to pay in ETH: 0.482872

Summary of work in this time period:
https://github.com/molochdao/ReallyBoringGuild-Bounty-Board/issues/33
https://github.com/molochdao/ReallyBoringGuild-Bounty-Board/issues/25
https://github.com/molochdao/ReallyBoringGuild-Bounty-Board/issues/24

## Payment Processing
**To be filled out by multisig member:**

* Date paid:
* Multisig Nonce: 
* Amount paid:

(link to multisig transaction here)

**Comment by poojaranjan** [comment]
Multisig tx 89 

Etherscan: https://etherscan.io/tx/0xf7484b5d574b0f63996900c3494dd08ae9cea49c825871bb581bc6fa85cb3c2b
